Feature
BenMukebo/gitflwotries pull request #1
Opened 2021-07-19 12:07 UTC by BenMukebo

In this feature, we have displayed something on the page

2021-07-19 12:12 UTC, hiromataba requested changes
### Dear Ben,

I think you should check my comments below and make the required changes

Thank you

Best,
Hiroi

2021-07-19 12:12 UTC, hiromataba commented on index.js
> +
I think you should not leave a lot spaces

2021-07-19 12:12 UTC, hiromataba commented on index.js
> + const output = mainDiv.innerHTML = `<p>Fuck you</p>`
Avoid hard words

2021-07-19 12:21 UTC, hiromataba approved these changes
Congratulations Ben

Your project is now ready to be merged 

thanks

2021-07-19 12:21 UTC, hiromataba commented on index.js
> +mainDiv.appendChild(output)
Thanks for making the changes

2021-07-19 12:23 UTC, merged

2021-07-20 08:31 UTC, BenMukebo commented
https://us05web.zoom.us/j/87853239993?pwd=QzBGTkV1TkdoODBxOVBFd3dhNVZlUT09


On Mon, Jul 19, 2021 at 2:21 PM Hiro Mataba ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Congratulations Ben
>
> Your project is now ready to be merged
>
> thanks
> ------------------------------
>
> In index.js
> <https://github.com/BenMukebo/gitflwotries/pull/1#discussion_r672247048>:
>
> > +const mainDiv = document.querySelector('.main-div');
> +const output = mainDiv.innerHTML = `<p>Hello World</p>`
> +mainDiv.appendChild(output)
>
> Thanks for making the changes
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BenMukebo/gitflwotries/pull/1#pullrequestreview-709480710>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS3FLPCSYEDA5H2ZJUYTUT3TYQKGLANCNFSM5ATSBEFQ>
> .
>

2021-09-30 13:57 UTC, BenMukebo commented
On Tue, Jul 20, 2021 at 10:31 AM Ben Mukebo ***@***.***>
wrote:

> https://us05web.zoom.us/j/87853239993?pwd=QzBGTkV1TkdoODBxOVBFd3dhNVZlUT09
>
>
> On Mon, Jul 19, 2021 at 2:21 PM Hiro Mataba ***@***.***>
> wrote:
>
>> ***@***.**** approved this pull request.
>>
>> Congratulations Ben
>>
>> Your project is now ready to be merged
>>
>> thanks
>> ------------------------------
>>
>> In index.js
>> <https://github.com/BenMukebo/gitflwotries/pull/1#discussion_r672247048>:
>>
>> > +const mainDiv = document.querySelector('.main-div');
>> +const output = mainDiv.innerHTML = `<p>Hello World</p>`
>> +mainDiv.appendChild(output)
>>
>> Thanks for making the changes
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/BenMukebo/gitflwotries/pull/1#pullrequestreview-709480710>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AS3FLPCSYEDA5H2ZJUYTUT3TYQKGLANCNFSM5ATSBEFQ>
>> .
>>
>